### ISSUE TITLE
build-tests.sh fail with a type error on OSX

### ISSUE THREAD

**Issue by vixr** [Victorian-Bioinformatics-Consortium/degust#22]
Getting the following error on OSX when I run build-tests.sh

~~~~
$ ./build-tests.sh
Building app/js/common-req.coffee -> tests/js/js-build/common.js
Building app/js/compare-req.coffee -> tests/js/js-build/compare.js
Building app/js/config-req.coffee -> tests/js/js-build/config.js
Building app/js/slickgrid-req.coffee -> tests/js/js-build/slickgrid.js
Building tests
TypeError: undefined is not a function
    at writeJs (/opt/local/lib/coffee-script/lib/coffee-script/command.js:413:17)
    at compileScript (/opt/local/lib/coffee-script/lib/coffee-script/command.js:185:18)
    at /opt/local/lib/coffee-script/lib/coffee-script/command.js:150:18
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)
~~~~

**Comment by drpowell** [comment]
Not much to go on there.  What version of coffeescript do you have?  It works for me with 1.7.1

**Comment by vixr** [comment]
I'm using the version installed by default using macports - 1.3.3

**Comment by drpowell** [comment]
I think that is probably too old.  I'd recommend install `npm` using homebrew, and coffeescript using `npm install -g coffee-script`
